<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
						color: #333;
						margin: 0;
						padding: 2rem;
						background-color: #f8fafc;
					}
					.container {
						max-width: 1000px;
						margin: 0 auto;
						background: #fff;
						padding: 2rem;
						border-radius: 1rem;
						box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
					}
					h1 {
						color: #1e293b;
						font-size: 1.875rem;
						font-weight: 800;
						margin-bottom: 1rem;
						display: flex;
						align-items: center;
						gap: 0.75rem;
					}
					.description {
						color: #64748b;
						margin-bottom: 2rem;
						line-height: 1.5;
					}
					table {
						width: 100%;
						border-collapse: collapse;
						margin-top: 1rem;
					}
					th {
						text-align: left;
						padding: 0.75rem;
						border-bottom: 2px solid #f1f5f9;
						color: #475569;
						font-size: 0.75rem;
						text-transform: uppercase;
						letter-spacing: 0.05em;
					}
					td {
						padding: 0.75rem;
						border-bottom: 1px solid #f1f5f9;
						color: #1e293b;
						font-size: 0.875rem;
						word-break: break-all;
					}
					tr:hover td {
						background-color: #f8fafc;
					}
					a {
						color: #f59e0b;
						text-decoration: none;
						font-weight: 600;
					}
					a:hover {
						text-decoration: underline;
					}
					.lastmod {
						color: #64748b;
						white-space: nowrap;
					}
					.count {
						background: #fef3c7;
						color: #92400e;
						padding: 0.25rem 0.75rem;
						border-radius: 9999px;
						font-size: 0.75rem;
						font-weight: 700;
					}
				</style>
			</head>
			<body>
				<div class="container">
					<h1>
						XML Sitemap
						<span class="count">
							<xsl:choose>
								<xsl:when test="sitemap:sitemapindex">
									<xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> Sitemaps
								</xsl:when>
								<xsl:otherwise>
									<xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs
								</xsl:otherwise>
							</xsl:choose>
						</span>
					</h1>
					<p class="description">
						Generated by EZMortgageLender.net. This is an XML Sitemap, meant for consumption by search engines.
						<br/>
						You can find more information about XML sitemaps on <a href="https://sitemaps.org">sitemaps.org</a>.
					</p>
					
					<xsl:if test="sitemap:sitemapindex">
						<table>
							<thead>
								<tr>
									<th>Sitemap URL</th>
									<th>Last Modified</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
									<tr>
										<td>
											<a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
										</td>
										<td class="lastmod">
											<xsl:value-of select="concat(substring(sitemap:lastmod, 0, 11), ' ', substring(sitemap:lastmod, 12, 5))"/>
										</td>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>
					
					<xsl:if test="sitemap:urlset">
						<table>
							<thead>
								<tr>
									<th>URL</th>
									<xsl:if test="sitemap:urlset/sitemap:url/sitemap:priority">
										<th>Priority</th>
									</xsl:if>
									<xsl:if test="sitemap:urlset/sitemap:url/sitemap:changefreq">
										<th>Frequency</th>
									</xsl:if>
									<th>Last Modified</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:urlset/sitemap:url">
									<tr>
										<td>
											<a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
										</td>
										<xsl:if test="sitemap:priority">
											<td><xsl:value-of select="sitemap:priority"/></td>
										</xsl:if>
										<xsl:if test="sitemap:changefreq">
											<td><xsl:value-of select="sitemap:changefreq"/></td>
										</xsl:if>
										<td class="lastmod">
											<xsl:value-of select="concat(substring(sitemap:lastmod, 0, 11), ' ', substring(sitemap:lastmod, 12, 5))"/>
										</td>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
